Stats dict to html list
hungry-ai/hungry-ai.github.io pull request #1
Opened 2023-04-04 19:07 UTC by nzmysd

Not sure if there was a way to write the html components (lines 60-63) using arrays but it's only 4 categories so works for now

2023-04-04 19:32 UTC, codercody requested changes

2023-04-04 19:32 UTC, codercody commented on src/components/Stats.js
> +]
Data will likely be fetched from the server in the following format:
```
{
  'Least favorite food': [
    {'Item': 'Food 1', 'Percent match': 95},
    {'Item': 'Food 2', 'Percent match': 90},
  ],
  ...
}
```
Is it possible to make the code work when `stats` looks like this?

2023-04-04 19:32 UTC, codercody commented on src/components/Stats.js
> +};
Instead of `x.category === 'undefined'` logic can we replace this with two `map`s? Something like (untested):
```
Object.entries(stats).map(
  ([statName, statValues]) => statValues.map(
    (value, index) => (
      <div>
        {index == 0 && <td>{statName}</td>}
        <td>{value["Item"]}</td>
        <td>{value["Percent match"]}</td>
      </div>
    )
  )
)
```

2023-04-04 19:32 UTC, codercody commented on src/components/Stats.js
> +export default function itemTable() {
Can we SPLIDD up this `export default` into
```
function itemTable() {
  ...
}

export default itemTable;
```
It's more flexible to changes that way

2023-04-04 19:32 UTC, codercody commented on src/components/Stats.js
> +export default function itemTable() {
It's best to use uppercase for react components so prefer `ItemTable` over `itemTable`.

2023-04-04 19:32 UTC, codercody commented on src/components/Stats.js
> +const statsTable4 = stats[3].map(itemMap)
No need to define variables for these one-line objects. Would prefer `{stats[0].map(itemMap)}` over
```
const statsTable1 = stats[0].map(itemMap)
...
{statsTable1}
```

2023-04-04 21:10 UTC, nzmysd commented on src/components/Stats.js
> +]
Now has this format: 
```
const stats = {
  "Favorite food": [
    { item: "Food 1", percentMatch: 95 },
    { item: "Food 2", percentMatch: 90 },
    { item: "Food 3", percentMatch: 85 },
  ],
...
}
```

2023-04-04 21:10 UTC, nzmysd commented on src/components/Stats.js
> +};
replaced with 2 maps

2023-04-04 21:11 UTC, nzmysd commented on src/components/Stats.js
> +export default function itemTable() {
SPLIDDed

2023-04-04 21:11 UTC, nzmysd commented on src/components/Stats.js
> +export default function itemTable() {
fixed

2023-04-04 21:11 UTC, nzmysd commented on src/components/Stats.js
> +const statsTable4 = stats[3].map(itemMap)
fixed

2023-04-05 00:57 UTC, codercody approved these changes
LGTM. I pushed some minor changes to main so if you could fix the merge conflicts then feel free to squash & merge. Thanks!!

2023-04-05 01:21 UTC, merged