issue #6
hungry-ai/hungry-ai.github.io pull request #7
Opened 2023-04-28 21:03 UTC by zozo-yasuda

[https://github.com/hungry-ai/hungry-ui/issues/6](url)
![image](https://user-images.githubusercontent.com/20708815/235253710-1e49c194-1094-4f8f-b8cc-35283faccd8f.png)

2023-04-28 21:22 UTC, codercody requested changes

2023-04-28 21:22 UTC, codercody commented on src/pages/Upload/index.js
> +    setImageURLs(newImageUrls);
I noticed if I upload one and then upload another, it removes the first one. So maybe start with newImageUrls = imageURLs

2023-04-28 21:22 UTC, codercody commented on src/pages/Upload/index.js
> +    images.forEach((image) => newImageUrls.push(URL.createObjectURL(image)));
Prefer `.map` over `.forEach(x => arr.push(x))`. So these two lines can be replaced with

```
const newImageUrls = [...imageURLs, ...images.map(URL.createObjectURL)]
```

2023-04-28 21:25 UTC, codercody commented on src/pages/Upload/index.js
> +  }, [images]);
Instead of a `useEffect(..., [images])` can we just put this in the `onImageChange`?

2023-04-29 19:44 UTC, zozo-yasuda commented on src/pages/Upload/index.js
> +    setImageURLs(newImageUrls);
fixed

2023-04-29 19:45 UTC, zozo-yasuda commented on src/pages/Upload/index.js
> +    images.forEach((image) => newImageUrls.push(URL.createObjectURL(image)));
fixed

2023-04-29 19:46 UTC, zozo-yasuda commented on src/pages/Upload/index.js
> +  }, [images]);
putting this in onImageChange makes it so that the preview is not shown on the first image uploaded (shows from second and on... I don't know why this is but I'll keep useEffect for now)

2023-05-29 16:41 UTC, codercody approved these changes
LGTM

2023-05-29 17:05 UTC, merged